name: GitHub Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: MatheusPerassolidev
          svg_out_path: github-contribution-grid-snake.svg   # ← direto na raiz

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .   # ← importante: raiz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
